In [1]:
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    import numpy as np
    df=pd.read_csv("C:/Users/user/Desktop/Cricket Analysis/Batting/ODI data.csv")

In [2]:
df

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,Unnamed: 13
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20,NaN
1,1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,NaN
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,NaN
3,3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.2,28,68,34,NaN
4,4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,45,ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-,NaN
2496,46,Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-,NaN
2497,47,Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-,NaN
2498,48,MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-,NaN
2499,49,GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-,NaN

In [3]:
df.columns.str.match("Unnamed")
df2=df.loc[:,~df.columns.str.match("Unnamed")]

In [4]:
df2.dtypes

Player    object
Span      object
Mat        int64
Inns      object
NO        object
Runs      object
HS        object
Ave       object
BF        object
SR        object
100       object
50        object
0         object
dtype: object

In [5]:
df2

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.2,28,68,34
4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-
2496,Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-
2497,Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-
2498,MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-
2499,GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-

In [6]:
df

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,Unnamed: 13
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20,NaN
1,1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,NaN
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,NaN
3,3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.2,28,68,34,NaN
4,4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,45,ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-,NaN
2496,46,Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-,NaN
2497,47,Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-,NaN
2498,48,MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-,NaN
2499,49,GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-,NaN

In [7]:
df2

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.2,28,68,34
4,DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-
2496,Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-
2497,Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-
2498,MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-
2499,GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-

In [8]:
df2.describe()

               Mat
count  2500.000000
mean     37.161600
std      58.885075
min       1.000000
25%       4.000000
50%      13.000000
75%      43.000000
max     463.000000

In [9]:
df2.Player

0              SR Tendulkar (INDIA)
1       KC Sangakkara (Asia/ICC/SL)
2              RT Ponting (AUS/ICC)
3           ST Jayasuriya (Asia/SL)
4        DPMD Jayawardene (Asia/SL)
                   ...
2495                ZS Ansari (ENG)
2496           Ariful Haque (BDESH)
2497             Ashfaq Ahmed (PAK)
2498                 MD Bailey (NZ)
2499                 GR Beard (AUS)
Name: Player, Length: 2500, dtype: object

In [10]:
df2.set_index("Player",inplace=True)

In [11]:
df2

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.2,28,68,34
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
...,...,...,...,...,...,...,...,...,...,...,...,...
ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-
Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-
Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-
MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-
GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-

In [12]:
df_best = df[["Player","Mat", "Inns", "NO", "Runs",
              "HS", "Ave", "BF","SR","100","50",'0']].copy()
df_best.set_index("Player",inplace=True)

In [13]:
df_best

,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,
SR Tendulkar (INDIA),463,452,41,18426,200*,44.83,21367,86.23,49,96,20
KC Sangakkara (Asia/ICC/SL),404,380,41,14234,169,41.98,18048,78.86,25,93,15
RT Ponting (AUS/ICC),375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),445,433,18,13430,189,32.36,14725,91.2,28,68,34
DPMD Jayawardene (Asia/SL),448,418,39,12650,144,33.37,16020,78.96,19,77,28
...,...,...,...,...,...,...,...,...,...,...,...
ZS Ansari (ENG),1,-,-,-,-,-,-,-,-,-,-
Ariful Haque (BDESH),1,-,-,-,-,-,-,-,-,-,-
Ashfaq Ahmed (PAK),3,-,-,-,-,-,-,-,-,-,-
MD Bailey (NZ),1,-,-,-,-,-,-,-,-,-,-
GR Beard (AUS),2,-,-,-,-,-,-,-,-,-,-

In [14]:
df2.tail(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
Shadab Kabir (PAK),1996-1996,3,3,0,0,0,0.00,5,0.00,0,0,3
Shakeel Khan (PAK),1987-1987,1,1,0,0,0,0.00,4,0.00,0,0,1
T Shamsi (SA),2016-2019,17,3,2,0,0*,0.00,2,0.00,0,0,1
Simandeep Singh (HKG),2018-2018,1,1,0,0,0,0.00,7,0.00,0,0,1
GS Sobers (WI),1973-1973,1,1,0,0,0,0.00,6,0.00,0,0,1
Tanvir Mehdi (PAK),1992-1992,1,1,0,0,0,0.00,5,0.00,0,0,1
M Venkataramana (INDIA),1988-1988,1,1,1,0,0*,-,0,-,0,0,0
R Walters (NAM),2003-2003,2,2,0,0,0,0.00,5,0.00,0,0,2
CM Willoughby (SA),2000-2003,3,2,0,0,0,0.00,4,0.00,0,0,2
Zakir Hossain (BDESH),1998-1998,1,1,0,0,0,0.00,1,0.00,0,0,1
Aamer Hameed (PAK),1977-1978,2,-,-,-,-,-,-,-,-,-,-
Abdur Rauf (PAK),2008-2008,4,-,-,-,-,-,-,-,-,-,-
Abu Jayed (BDESH),2019-2019,2,-,-,-,-,-,-,-,-,-,-
FS Ahangama (SL),1985-1985,1,-,-,-,-,-,-,-,-,-,-
GW Aldridge (NZ),2011-2011,2,-,-,-,-,-,-,-,-,-,-
ZS Ansari (ENG),2015-2015,1,-,-,-,-,-,-,-,-,-,-
Ariful Haque (BDESH),2018-2018,1,-,-,-,-,-,-,-,-,-,-
Ashfaq Ahmed (PAK),1994-1994,3,-,-,-,-,-,-,-,-,-,-
MD Bailey (NZ),1998-1998,1,-,-,-,-,-,-,-,-,-,-
GR Beard (AUS),1981-1981,2,-,-,-,-,-,-,-,-,-,-

In [15]:
df2.tail(10)

                           Span  Mat Inns NO Runs HS Ave BF SR 100 50  0
Player
Aamer Hameed (PAK)    1977-1978    2    -  -    -  -   -  -  -   -  -  -
Abdur Rauf (PAK)      2008-2008    4    -  -    -  -   -  -  -   -  -  -
Abu Jayed (BDESH)     2019-2019    2    -  -    -  -   -  -  -   -  -  -
FS Ahangama (SL)      1985-1985    1    -  -    -  -   -  -  -   -  -  -
GW Aldridge (NZ)      2011-2011    2    -  -    -  -   -  -  -   -  -  -
ZS Ansari (ENG)       2015-2015    1    -  -    -  -   -  -  -   -  -  -
Ariful Haque (BDESH)  2018-2018    1    -  -    -  -   -  -  -   -  -  -
Ashfaq Ahmed (PAK)    1994-1994    3    -  -    -  -   -  -  -   -  -  -
MD Bailey (NZ)        1998-1998    1    -  -    -  -   -  -  -   -  -  -
GR Beard (AUS)        1981-1981    2    -  -    -  -   -  -  -   -  -  -

In [16]:
df2=df2.replace("-", np.nan)

In [17]:
df2.tail(10)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
Aamer Hameed (PAK),1977-1978,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abdur Rauf (PAK),2008-2008,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abu Jayed (BDESH),2019-2019,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FS Ahangama (SL),1985-1985,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GW Aldridge (NZ),2011-2011,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZS Ansari (ENG),2015-2015,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ariful Haque (BDESH),2018-2018,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ashfaq Ahmed (PAK),1994-1994,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MD Bailey (NZ),1998-1998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GR Beard (AUS),1981-1981,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df2=df2.fillna(0)

In [19]:
df2.dtypes

Span    object
Mat      int64
Inns    object
NO      object
Runs    object
HS      object
Ave     object
BF      object
SR      object
100     object
50      object
0       object
dtype: object

In [20]:
df2.dtypes

Span    object
Mat      int64
Inns    object
NO      object
Runs    object
HS      object
Ave     object
BF      object
SR      object
100     object
50      object
0       object
dtype: object

In [21]:
df2["Inns"] = df2["Inns"].fillna(0).astype(np.int64, errors='ignore')

In [22]:
df2["NO"] = df2["NO"].fillna(0).astype(np.int64, errors='ignore')
df2["Runs"] = df2["Runs"].fillna(0).astype(np.int64, errors='ignore')
df2["HS"] = df2["HS"].fillna(0).astype(np.int64, errors='ignore')
df2["Ave"] = df2["Ave"].fillna(0).astype(np.float64, errors='ignore')
df2["BF"] = df2["BF"].fillna(0).astype(np.int64, errors='ignore')
df2["SR"] = df2["SR"].fillna(0).astype(np.float64, errors='ignore')
df2["100"] = df2["100"].fillna(0).astype(np.int64, errors='ignore')
df2["50"] = df2["50"].fillna(0).astype(np.int64, errors='ignore')
df2["0"] = df2["0"].fillna(0).astype(np.int64, errors='ignore')

In [23]:
df2.dtypes

Span     object
Mat       int64
Inns      int64
NO        int64
Runs      int64
HS       object
Ave     float64
BF        int64
SR      float64
100       int64
50        int64
0         int64
dtype: object

In [24]:
df2

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
...,...,...,...,...,...,...,...,...,...,...,...,...
ZS Ansari (ENG),2015-2015,1,0,0,0,0,0.00,0,0.00,0,0,0
Ariful Haque (BDESH),2018-2018,1,0,0,0,0,0.00,0,0.00,0,0,0
Ashfaq Ahmed (PAK),1994-1994,3,0,0,0,0,0.00,0,0.00,0,0,0
MD Bailey (NZ),1998-1998,1,0,0,0,0,0.00,0,0.00,0,0,0
GR Beard (AUS),1981-1981,2,0,0,0,0,0.00,0,0.00,0,0,0

# Most Innings Played

In [25]:
most_inns=df2.sort_values(by='Inns',inplace=False,ascending=False)
most_inns.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
Shahid Afridi (Asia/ICC/PAK),1996-2015,398,369,27,8064,124,23.57,6892,117.00,6,39,30
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
Inzamam-ul-Haq (Asia/PAK),1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83,20
R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15284,71.24,12,83,13
JH Kallis (Afr/ICC/SA),1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86,17
M Azharuddin (INDIA),1985-2000,334,308,54,9378,153*,36.92,12669,74.02,7,58,9
TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16
MS Dhoni (Asia/INDIA),2004-2019,350,297,84,10773,183*,50.57,12303,87.56,10,73,10
PA de Silva (SL),1984-2003,308,296,30,9284,145,34.90,11443,81.13,11,64,17
CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25
BC Lara (ICC/WI),1990-2007,299,289,32,10405,169,40.48,13086,79.51,19,63,16
SR Waugh (AUS),1986-2002,325,288,58,7569,120*,32.90,9971,75.91,3,45,15
Wasim Akram (PAK),1984-2003,356,280,55,3717,86,16.52,4208,88.33,0,6,28
AC Gilchrist (AUS/ICC),1996-2008,287,279,11,9619,172,35.89,9922,96.94,16,55,19
Yuvraj Singh (Asia/INDIA),2000-2017,304,278,40,8701,150,36.55,9924,87.67,14,52,18

# Most Runs Scored

In [26]:
most_runs=df2.sort_values(by='Runs',inplace=False,ascending=False)
most_runs.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
Inzamam-ul-Haq (Asia/PAK),1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83,20
V Kohli (INDIA),2008-2019,242,233,39,11609,183,59.84,12445,93.28,43,55,13
JH Kallis (Afr/ICC/SA),1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86,17
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16
R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15284,71.24,12,83,13
MS Dhoni (Asia/INDIA),2004-2019,350,297,84,10773,183*,50.57,12303,87.56,10,73,10
CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25
BC Lara (ICC/WI),1990-2007,299,289,32,10405,169,40.48,13086,79.51,19,63,16
TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11
Mohammad Yousuf (Asia/PAK),1998-2010,288,273,40,9720,141*,41.71,12942,75.10,15,64,15
AC Gilchrist (AUS/ICC),1996-2008,287,279,11,9619,172,35.89,9922,96.94,16,55,19
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7
M Azharuddin (INDIA),1985-2000,334,308,54,9378,153*,36.92,12669,74.02,7,58,9
PA de Silva (SL),1984-2003,308,296,30,9284,145,34.90,11443,81.13,11,64,17
RG Sharma (INDIA),2007-2019,221,214,32,8944,264,49.14,10063,88.88,28,43,13

# Best Average (Min runs 2000)

In [27]:
#best_ave=df2.sort_values(by='Ave',inplace=False,ascending=False)
#best_ave.head(20)
filtered_df = df2[df2['Runs'] >= 2000]
best_ave = filtered_df.sort_values('Ave', inplace=False,ascending=False)
best_ave.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
V Kohli (INDIA),2008-2019,242,233,39,11609,183,59.84,12445,93.28,43,55,13
Babar Azam (PAK),2015-2019,74,72,10,3359,125*,54.17,3857,87.08,11,15,2
MG Bevan (AUS),1994-2004,232,196,67,6912,108*,53.58,9320,74.16,6,46,5
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7
SD Hope (WI),2016-2019,72,67,10,3007,170,52.75,4046,74.32,8,15,4
JE Root (ENG),2013-2019,143,135,21,5856,133*,51.36,6702,87.37,16,33,4
IJL Trott (ENG),2009-2013,68,65,10,2819,137,51.25,3658,77.06,4,22,5
MS Dhoni (Asia/INDIA),2004-2019,350,297,84,10773,183*,50.57,12303,87.56,10,73,10
HM Amla (SA),2008-2019,181,178,14,8113,159,49.46,9178,88.39,27,39,4
RG Sharma (INDIA),2007-2019,221,214,32,8944,264,49.14,10063,88.88,28,43,13
MEK Hussey (AUS),2004-2012,185,157,44,5442,109*,48.15,6243,87.16,3,39,3
KS Williamson (NZ),2010-2019,149,142,14,6132,148,47.90,7494,81.82,13,39,5
LRPL Taylor (NZ),2006-2019,228,212,37,8376,181*,47.86,10091,83.00,20,50,9
JM Bairstow (ENG),2011-2019,74,68,8,2861,141*,47.68,2749,104.07,9,11,5
Zaheer Abbas (PAK),1974-1985,62,60,6,2572,123,47.62,3033,84.80,7,13,2
F du Plessis (SA),2011-2019,143,136,20,5507,185,47.47,6215,88.60,12,35,3
IVA Richards (WI),1975-1991,187,167,24,6721,189*,47.00,7451,90.20,11,45,7
DA Warner (AUS),2009-2019,116,114,5,4990,179,45.77,5222,95.55,17,20,2
CG Greenidge (WI),1975-1991,128,127,13,5134,133*,45.03,7908,64.92,11,31,3
Q de Kock (SA),2013-2019,115,115,6,4907,178,45.01,5154,95.20,14,24,3

# Highest Score (Min 2000 runs and 20+ centuries )

In [28]:
filtered_df2 = df2[(df2['Runs'] >= 2000) & (df2['100'] >= 20)]
hi_sr = filtered_df2.sort_values('SR', inplace=False,ascending=False)
hi_sr.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7
V Kohli (INDIA),2008-2019,242,233,39,11609,183,59.84,12445,93.28,43,55,13
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
RG Sharma (INDIA),2007-2019,221,214,32,8944,264,49.14,10063,88.88,28,43,13
HM Amla (SA),2008-2019,181,178,14,8113,159,49.46,9178,88.39,27,39,4
CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11
HH Gibbs (SA),1996-2010,248,240,16,8094,175,36.13,9721,83.26,21,37,22
LRPL Taylor (NZ),2006-2019,228,212,37,8376,181*,47.86,10091,83.00,20,50,9
Saeed Anwar (PAK),1989-2003,247,244,19,8824,194,39.21,10938,80.67,20,43,15
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16

# Most 100s

In [29]:
most_hund = filtered_df.sort_values('100', inplace=False,ascending=False)
most_hund.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
V Kohli (INDIA),2008-2019,242,233,39,11609,183,59.84,12445,93.28,43,55,13
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
RG Sharma (INDIA),2007-2019,221,214,32,8944,264,49.14,10063,88.88,28,43,13
HM Amla (SA),2008-2019,181,178,14,8113,159,49.46,9178,88.39,27,39,4
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16
TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11
HH Gibbs (SA),1996-2010,248,240,16,8094,175,36.13,9721,83.26,21,37,22
LRPL Taylor (NZ),2006-2019,228,212,37,8376,181*,47.86,10091,83.00,20,50,9
Saeed Anwar (PAK),1989-2003,247,244,19,8824,194,39.21,10938,80.67,20,43,15
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
BC Lara (ICC/WI),1990-2007,299,289,32,10405,169,40.48,13086,79.51,19,63,16
ME Waugh (AUS),1988-2002,244,236,20,8500,173,39.35,11053,76.90,18,50,16
DA Warner (AUS),2009-2019,116,114,5,4990,179,45.77,5222,95.55,17,20,2
DL Haynes (WI),1978-1994,238,237,28,8648,152*,41.37,13707,63.09,17,57,13
S Dhawan (INDIA),2010-2019,133,131,7,5518,143,44.50,5869,94.01,17,27,5

# Most 100s (With less than 10 0s)

In [30]:
filtered_df3 = df2[(df2['Runs'] >= 2000) & (df2['100'] >= 20) & (df2['0'] < 10)]
most_hund_0 = filtered_df3.sort_values('SR', inplace=False,ascending=False)
most_hund_0.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7
HM Amla (SA),2008-2019,181,178,14,8113,159,49.46,9178,88.39,27,39,4
LRPL Taylor (NZ),2006-2019,228,212,37,8376,181*,47.86,10091,83.00,20,50,9

# Most 50s

In [31]:
most_50=df2.sort_values(by='50',inplace=False,ascending=False)
most_50.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0
Player,,,,,,,,,,,,
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
JH Kallis (Afr/ICC/SA),1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86,17
Inzamam-ul-Haq (Asia/PAK),1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83,20
R Dravid (Asia/ICC/INDIA),1996-2011,344,318,40,10889,153,39.16,15284,71.24,12,83,13
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
DPMD Jayawardene (Asia/SL),1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77,28
MS Dhoni (Asia/INDIA),2004-2019,350,297,84,10773,183*,50.57,12303,87.56,10,73,10
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
PA de Silva (SL),1984-2003,308,296,30,9284,145,34.90,11443,81.13,11,64,17
Mohammad Yousuf (Asia/PAK),1998-2010,288,273,40,9720,141*,41.71,12942,75.10,15,64,15
BC Lara (ICC/WI),1990-2007,299,289,32,10405,169,40.48,13086,79.51,19,63,16
S Chanderpaul (WI),1994-2011,268,251,40,8778,150,41.60,12408,70.74,11,59,6
MS Atapattu (SL),1990-2007,268,259,32,8529,132*,37.57,12594,67.72,11,59,13
M Azharuddin (INDIA),1985-2000,334,308,54,9378,153*,36.92,12669,74.02,7,58,9
MJ Clarke (AUS),2003-2015,245,223,44,7981,130,44.58,10104,78.98,8,58,10
DL Haynes (WI),1978-1994,238,237,28,8648,152*,41.37,13707,63.09,17,57,13
A Flower (ZIM),1992-2003,213,208,16,6786,145,35.34,9097,74.59,4,55,13
AC Gilchrist (AUS/ICC),1996-2008,287,279,11,9619,172,35.89,9922,96.94,16,55,19

# Best Conversion Rate

In [49]:
filtered_df4 = df2[(df2['100'] > 0) & (df2['50'] > 0) & (df2['100'] >= 20)].copy()

filtered_df4['ratio'] = (filtered_df4['100'] / filtered_df4['50'])*100

best_conversion=filtered_df4.sort_values(by='ratio',inplace=False,ascending=False)
best_conversion.head(20)

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,ratio
Player,,,,,,,,,,,,,
V Kohli (INDIA),2008-2019,242,233,39,11609,183,59.84,12445,93.28,43,55,13,78.181818
HM Amla (SA),2008-2019,181,178,14,8113,159,49.46,9178,88.39,27,39,4,69.230769
RG Sharma (INDIA),2007-2019,221,214,32,8944,264,49.14,10063,88.88,28,43,13,65.116279
HH Gibbs (SA),1996-2010,248,240,16,8094,175,36.13,9721,83.26,21,37,22,56.756757
SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21367,86.23,49,96,20,51.041667
AB de Villiers (Afr/SA),2005-2018,228,218,39,9577,176,53.50,9473,101.09,25,53,7,47.169811
TM Dilshan (SL),1999-2016,330,303,41,10290,161*,39.27,11933,86.23,22,47,11,46.808511
Saeed Anwar (PAK),1989-2003,247,244,19,8824,194,39.21,10938,80.67,20,43,15,46.511628
CH Gayle (ICC/WI),1999-2019,301,294,17,10480,215,37.83,12019,87.19,25,54,25,46.296296
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,41.176471
LRPL Taylor (NZ),2006-2019,228,212,37,8376,181*,47.86,10091,83.00,20,50,9,40.000000
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,36.585366
SC Ganguly (Asia/INDIA),1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72,16,30.555556
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15,26.881720